[toolchain]
package_manager = "pnpm"

[features]
resolution = true
skip-lint = false

[programs.devnet]
betting_pools_2 = "9nW58a3uYAveyKAxpytoSwobwGTMm4QHJwzKiiGK7RXK"

[programs.localnet]
betting_pools_2 = "9nW58a3uYAveyKAxpytoSwobwGTMm4QHJwzKiiGK7RXK"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/canibeton.json"

[scripts]
test = "pnpm ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
