[toolchain]
package_manager = "pnpm"

[features]
resolution = true
skip-lint = false

[programs.devnet]
betting_pools_2 = "E3V6czvYpjrdZVTLwFKzrw3GhCvH1LXKijADCkahw7QF"

[programs.localnet]
betting_pools_2 = "6qXrYhcXYzKDCU6XoSJY94oNGF4QZ31KGbmUTDW8YQPP"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/canibeton.json"

[scripts]
test = "pnpm ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
