// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.3
import { Reader, Writer } from 'as-proto/assembly';

export class PoolMediaSet_Event {
  static encode(message: PoolMediaSet_Event, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.txHash);

    writer.uint32(16);
    writer.uint64(message.poolId);

    writer.uint32(26);
    writer.string(message.mediaUrl);

    writer.uint32(32);
    writer.int32(message.mediaType);
  }

  static decode(reader: Reader, length: i32): PoolMediaSet_Event {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new PoolMediaSet_Event();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.txHash = reader.string();
          break;

        case 2:
          message.poolId = reader.uint64();
          break;

        case 3:
          message.mediaUrl = reader.string();
          break;

        case 4:
          message.mediaType = reader.int32();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  txHash: string;
  poolId: u64;
  mediaUrl: string;
  mediaType: i32;

  constructor(txHash: string = '', poolId: u64 = 0, mediaUrl: string = '', mediaType: i32 = 0) {
    this.txHash = txHash;
    this.poolId = poolId;
    this.mediaUrl = mediaUrl;
    this.mediaType = mediaType;
  }
}
