#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Run codegen
echo "Running codegen in frontend..."
bun --cwd frontend codegen
echo "Running codegen in graph..."
bun --cwd graph codegen

# Run lint-staged (eslint fix and prettier)
echo "Running lint and format..."
bun lint-staged

# Build everything
echo "Building the project..."
bun run build

echo "Pre-commit hook completed successfully!"
